class CategoryGenerator
  def initialize
    @bank_transfers_id = create_category(title: 'Bank Transfers').id
    @online_wallets_id = create_category(title: 'Online Wallets').id
    @gift_cards_id = create_category(title: 'Gift Cards').id
    @cash_id = create_category(title: 'Cash').id
    @credit_cards_id = create_category(title: 'Debit/Credit Cards').id
    @cryptocurrencies_id = create_category(title: 'Cryptocurrencies').id
  end

  def self.generate!
    new.generate!
    Category.rebuild_depth_cache!
  end

  def generate!
    generate_bank_transfers
    generate_online_wallets
    generate_gift_cards
    generate_cash
    generate_credit_cards
    generate_cryptocurrencies
  end

  def generate_bank_transfers
    [
      'Bank Transfer',
      'Domestic Wire Transfer',
      'Faster Payment System (FPS)',
      'IMPS Transfer',
      'Interac Online',
      'International Wire Transfer (SWIFT)',
      'PayID',
      'SEPA',
      'UPI Transfer'
    ].map do |title|
      TradeItem.create(title: title, category_id: @bank_transfers_id)
    end
  end

  def generate_online_wallets
    [
      'Abra',
      'AdvCash',
      'Airline Tickets',
      'Airtel Money',
      'AirTM',
      'Alipay',
      'AlipayHK',
      'ApplePay',
      'AstroPay Direct',
      'Bhim',
      'Bill Payment',
      'Bitwallet',
      'Bkash E-Wallet',
      'Bunq Transfer',
      'Capital One 360 P2P Payment',
      'Cash App',
      'CashU',
      'Chase Quickpay',
      'Chime Instant Transfers',
      'ChimpChange Mobile Banking',
      'Chipper Cash',
      'CIB Smart Wallet',
      'Circle Pay',
      'Easy Paisa',
      'eCheck',
      'EcoCash',
      'ecoPayz',
      'ePay',
      'Equitel Mobile Money',
      'Esewa',
      'Etisalat Cash',
      'Facebook Messenger Payment',
      'FasaPay Online Payment',
      'Flashpay Netspend',
      'FNB E-WALLET',
      'GCash',
      'GoFundMe.com',
      'Goods and Services',
      'Google Pay',
      'GrabPay',
      'GönderAL',
      'Hilton HHonors Points',
      'Interac e-Transfer',
      'KaKaoPay',
      'LeoPay',
      'Line Pay',
      'LiqPay',
      'Lydia',
      'M-Pesa',
      'mCash Mobile Payment',
      'Mercado Pago',
      'Mobile Recharge',
      'MobilePay',
      'Mobivi',
      'Moca',
      'Momo',
      'Monese Online Transfer',
      'MovoCash Transfer',
      'mPayVN',
      'MTN Mobile Money',
      'N26',
      'NBE Phone Cash',
      'Neteller',
      'NganLuong',
      'OkPay',
      'Ononpay',
      'Opal Transfer',
      'Orange Money',
      'Paga Wallet',
      'Pago Fácil',
      'Paxum',
      'Payeer',
      'PayM',
      'PayMe',
      'Payoneer',
      'Payoo',
      'PayPal',
      'Paypower',
      'Paysend.com',
      'Paysera Money Transfer',
      'PaySon',
      'Paytm Online Wallet',
      'Payza',
      'Perfect Money',
      'PhonePe',
      'PIM',
      'Pingit',
      'PlusGirot',
      'Pokerstars',
      'Popmoney',
      'Qiwi',
      'QNB Smart Wallet',
      'Quickteller',
      'Rapipago',
      'Remitly',
      'Revolut',
      'Rocket Remit',
      'Simple Bank App',
      'Skrill',
      'SoFi Money Instant Transfer',
      'Sofort',
      'SolidTrust Pay',
      'Square Up',
      'Straight Talk Reload',
      'Stripe',
      'Swish',
      'T-kash',
      'Tarjeta PAGO24',
      'Tarjeta PREX',
      'Tarjeta UALA',
      'Tele2',
      'Tigo Pesa',
      'Toss Wallet',
      'TransferWise',
      'TrueMoney',
      'UGO Pay',
      'UnionPay (App)',
      'Uphold',
      'Venmo',
      'ViettelPay',
      'VoguePay',
      'Wave App',
      'WebMoney',
      'WeChat Pay',
      'Wells Fargo SurePay',
      'Xoom Money Transfer',
      'Yandex.Money',
      'ZaloPay',
      'Zelle Pay'
    ].map do |title|
      TradeItem.create(title: title, category_id: @online_wallets_id)
    end
  end

  def generate_gift_cards
    [
      'T-Mobile Refill',
      'Adidas Gift Card',
      'AirBnb Gift Card',
      'Amazon Gift Card',
      'Amazon Wishlist',
      'AMC Theaters Gift Card',
      'American Apparel Gift Card',
      'American Express Card',
      'Any Visa, MasterCard and AmEx Gift Cards',
      'Apple Store Gift Card',
      "Applebee's Restaurant Gift Card",
      'Asos Gift Card',
      'AT&T Gift Card',
      'Barnes & Noble Gift Card',
      'Bed Bath & Beyond Gift Card',
      'Best Buy Gift Card',
      'Blizzard Gift Card',
      'Booking.com Gift Cards',
      'Boost Mobile',
      "Cabela's E-Gift Code",
      'Calvin Klein Gift Card',
      'CASHlib Vouchers',
      "Chili's Restaurant Gift Card",
      'Coles Gift Card',
      'Costco Cash Card',
      'Cracker Barrel Gift Card',
      'CVS Gift Card',
      'Dell Gift Card',
      'Delta Air Line Gift Card',
      'Disney Gift Cards',
      'DMM Prepaid Card',
      "Domino's Pizza Gift Card",
      "Dunkin' Donuts Card",
      'Eastbay Gift Card',
      'eBay Gift Card',
      'eGifter.com Code',
      'Etsy',
      'Everlane Gift Card',
      'Fandango Gift Card',
      'Finish Line Gift Card',
      'Flexepin Gift Card',
      'Flipkart e-Gift Voucher',
      'Forever 21 Gift Card',
      'FreshDirect Gift Card',
      'G2A Gift Card',
      'GameStop Gift Card',
      'Gift Cards (Miscellaneous  Retailers)',
      'Giftcards.nl Redeem Choice Card',
      'Google Play Gift Card',
      'Groupon Gift Card',
      'H&M Gift Card',
      'Home Depot Gift Card',
      'Hotels.com Gift Card',
      'HULU Gift Card',
      'Hyatt eGift Card',
      'IHOP Gift Card',
      'IKEA Gift Card',
      'iTunes Gift Card',
      "Jason's Deli Gift Cards",
      'JCPenney Gift Card',
      "Lowe's Gift Card",
      'Lyft Gift Card',
      "Macy's Gift Card",
      'MasterCard Gift Card',
      'Microsoft Gift Card',
      'MoneyPak',
      'Myer Gift Card',
      'Neosurf Gift Card',
      'Netflix Gift Card',
      'Newegg Gift Card',
      'Nike Gift Card',
      'Nintendo eShop Digital Card / Gift Card',
      'Nordstrom Gift Card',
      'Offgamers.com Gift Card',
      'Office Depot Gift Card',
      'Olive Garden Restaurant Gift Card',
      'OneVanilla VISA/MasterCard Gift Card',
      'Papa Johns Gift Card',
      'PCS Prepaid Cash Services',
      'Pizza Hut Gift Card',
      'Playstation Network Gift Card',
      'Quiksilver Gift Card',
      'Reebok Gift Card',
      'Reloadit by Netspend',
      'Restaurant Gift Cards (Various Retailers)',
      'Riot Points League of Legends',
      'Roblox Game Card',
      'Safeway Gift Card',
      'Saks Fifth Avenue Gift Card',
      'Sears Gift Card',
      'Sephora Gift Card',
      'Skype Credits',
      'Southwest Airlines Gift Card',
      'Spotify Gift Card',
      'Staples Gift Card',
      'Starbucks Card',
      'Steam Wallet Gift Card',
      'Subway Gift Card',
      'Target Gift Card',
      'TicketMaster Gift Card',
      'Ticket Premium Gift Card',
      'Uber Gift Card',
      'Ulta Gift Card',
      'United Airlines Gift Card',
      "Victoria's Secret Gift Card",
      'VISA Gift Card',
      'Walmart Gift Card',
      'Walmart Visa Gift Card',
      'Whole Foods Market Gift Card',
      'Xbox Gift Card ',
      'Zappos Gift Card'
    ].map do |title|
      TradeItem.create(title: title, category_id: @gift_cards_id)
    end
  end

  def generate_cash
    [
      'Amazon Cash',
      'Bancolombia Cash Deposit',
      'BB&T Cash Deposit',
      'BBVA Compass Cash Deposit',
      'Bitcoin ATM',
      'BMO Cash Deposit',
      'BMO Harris Cash Deposit',
      'BPI & Cebuana Lhuiller',
      'Capital One Cash Deposit',
      'Cardless Cash',
      'Cash By Mail',
      'Cash deposit (Coinstar Kiosk)',
      'Cash Deposit: Capitol One',
      'Cash Deposit Navy Federal Credit Union',
      'Cash Deposit to Bank',
      'Cash deposit to CBA or Westpac',
      'Cash Deposit: ANZ',
      'Cash deposit: ANZ, ASB, BNZ, KIWI, WESTPAC',
      'Cash Deposit: BPI',
      'Cash deposit: CBA/WestPac/NAB/ANZ',
      'Cash Deposit: CSOB ATMs',
      'Cash Deposit: CSOB Branches & ATMs',
      'Cash Deposit: Westpac',
      'Cash in Person',
      "Cashier's check",
      'Cebuana Lhuiller Pawn Shops',
      'Chase Cash Deposit',
      'Check',
      'CIBC Cash Deposit',
      'CO-OP Credit Unions Cash Deposit',
      'Community First Credit Union Cash Deposit',
      'EzRemit',
      'HSBC Cash Deposit',
      'La Banque Postale Cash Deposit',
      'M&T Cash Deposit',
      'MoneyGram',
      'NAB Cash Deposit',
      'OXXO',
      'PayPoint',
      'PNC Cash Deposit',
      'Postal Money Order',
      'Rbs/Natwest/Ulster Cash Deposit',
      'Regions Cash Deposit',
      'RIA Money Transfer',
      'St George Cash Deposit',
      'Suntrust Cash Deposit',
      'Target VISA Gift Card',
      'Vodafone Cash Egypt',
      'Walmart to Walmart',
      'Walmart/CVS/7-Eleven Cash Deposit',
      'Wells Fargo Cardless ATM',
      'Wells Fargo Cash Deposit',
      'Western Union',
      'Westpac - Cash Deposit',
      'Xpress Money Service'
    ].map do |title|
      TradeItem.create(title: title, category_id: @cash_id)
    end
  end

  def generate_credit_cards
    [
      'AccountNow Prepaid Card',
      'Akimbo',
      'American Express Gift Card',
      'ANY Credit/Debit Card',
      'Bluebird American Express',
      'Card.com Transfer',
      'Discover Credit Cards',
      'GreenDot Card',
      'Kroger Recharge Card',
      'Kroger to Kroger Prepaid',
      'Mango Card2Card',
      'MyVanilla Prepaid Card',
      'Paysafecard',
      'PostePay',
      'Prepaid Debit Card',
      'READYdebit Prepaid Card',
      'RushCard Prepaid Visa',
      'Serve to Serve',
      'Visa Debit/Credit Card',
      'Walmart MoneyCard'
    ].map do |title|
      TradeItem.create(title: title, category_id: @credit_cards_id)
    end
  end

  def generate_cryptocurrencies
    ['Bitcoin BTC', 'Monero XMR'].map do |title|
      TradeItem.create(title: title, category_id: @cryptocurrencies_id)
    end
  end

  private

  def create_category(title:)
    Category.create(title: title, parent_id: nil)
  end
end
